# Generated by Django 3.1.6 on 2021-10-06 12:23

from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RefCropType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Нэр')),
                ('is_active', models.BooleanField(default=False, verbose_name='Идэвхтэй эсэх')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='Эрэмбэ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
            ],
            options={
                'verbose_name': 'Ургамлын төрөл',
                'verbose_name_plural': 'Ургамлын төрлүүд',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RefListingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Нэр')),
                ('is_active', models.BooleanField(default=False, verbose_name='Идэвхтэй эсэх')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='Эрэмбэ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
            ],
            options={
                'verbose_name': 'Listing type',
                'verbose_name_plural': 'Listing types',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RefNewsFeed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Нэр')),
                ('is_active', models.BooleanField(default=False, verbose_name='Идэвхтэй эсэх')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='Эрэмбэ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
                ('topic', models.CharField(max_length=100, verbose_name='topic')),
            ],
            options={
                'verbose_name': 'RefNewsFeed',
                'verbose_name_plural': 'RefNewsFeeds',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RefPlanting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Нэр')),
                ('is_active', models.BooleanField(default=False, verbose_name='Идэвхтэй эсэх')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='Эрэмбэ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
            ],
            options={
                'verbose_name': 'Тарих арга',
                'verbose_name_plural': 'Тарих аргууд',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RefProvince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Нэр')),
                ('is_active', models.BooleanField(default=False, verbose_name='Идэвхтэй эсэх')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='Эрэмбэ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
            ],
            options={
                'verbose_name': 'Аймаг',
                'verbose_name_plural': 'Аймгууд',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='RefSum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Нэр')),
                ('is_active', models.BooleanField(default=False, verbose_name='Идэвхтэй эсэх')),
                ('sort_order', models.IntegerField(blank=True, null=True, verbose_name='Эрэмбэ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
                ('lat', models.FloatField(default=0.0)),
                ('lon', models.FloatField(default=0.0)),
                ('ref_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='references.refprovince')),
            ],
            options={
                'verbose_name': 'Сум',
                'verbose_name_plural': 'Сумууд',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Таримал')),
                ('icon', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='crop/icon')),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='crop/image')),
                ('is_mobile_home', models.BooleanField(default=False)),
                ('ref_crop_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='references.refcroptype', verbose_name='Төрөл ')),
            ],
            options={
                'verbose_name': 'Таримал',
                'verbose_name_plural': 'Тарималууд',
            },
        ),
    ]
